### PR TITLE
deleted a deprecated method call

### PR DESCRIPTION
**Pull request by SZinedine**
QLayout::setMargin is deprecated (and provokes a compilation error when included in a project and compiled against a recent Qt version) and redundent in this case since QLayout::setContentsMargins does exactly the same thing

### CODE REVIEW

**Comment by pbek** [comment]
Is there a substitute for `setMargin`? I couldn't find any. qmarkdowntextedit needs to work with Qt 5.3.

**Comment by Waqar144** [comment]
best to wrap it with `#ifdef`

**Comment by pbek** [comment]
> best to wrap it with `#ifdef`

yes, but that would only be my 2nd best choice, because that still doesn't solve the problem for Qt >= 5.13 :grin:

**Comment by pbek** [comment]
https://doc.qt.io/qt-5/qlayout-obsolete.html#margin-prop

I guess in this case it is really the same
